# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# mpirun --allow-run-as-root -np 8 python train.py --config-name=config_train_diffusion.yaml hydra.job.name=dif_8gpu regression_checkpoint_path=./outputs/reg_8gpu/output_regression/training-state-regression-000666.mdlus

hydra:
  job:
    chdir: true
    name: diffusion_job
  run:
    dir: ./outputs/${hydra:job.name}
      
defaults:
  - config_train_base

batch_size_gpu: 4
  # Limit batch size per GPU
duration: 100
  # Training duration
lr: 0.001
  # Learning rate
lr_rampup_kimg: 100
  # Learning rate ramp-up duration.
ema: 0.5
  # EMA half-life, ema_halflife_kimg = int(ema * 1000), ema_halflife_nimg = ema_halflife_kimg * 1000
  # regression doesn't really need ema, so set a very high value here.
dump: 200
  # How often to dump state
validation_dump: 100
  # how often to record the validation loss


## Main options
outdir: "./output_diffusion"   
  # Where to save the results
arch: ddpmpp-cwb
  # Network architecture [ddpmpp, ddpmpp-cwb, ncsnpp, adm, ddpmpp-cwb-v0-regression]
precond: resloss
  # Preconditioning & loss function [vp, ve, edm, unetregression, resloss]
task: diffusion
  # Which model to train [regression, diffusion]

## I/O
regression_checkpoint_path: checkpoints/regression.mdlus
  # Where to save the checkpoints
